package com.mine.product.czmtr.ram.asset.taskclient;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-28T11:02:52.815+08:00
 * Generated source version: 3.3.3
 */
@WebServiceClient(name = "GetMaterialsDataImplService",
        wsdlLocation = "http://10.0.52.206:7001/czx-web/webservice/getequipcodes?wsdl",
        targetNamespace = "http://getequipcodes.api.adam.hitina.net/")
public class GetMaterialsDataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://getequipcodes.api.adam.hitina.net/", "GetMaterialsDataImplService");
    public final static QName GetMaterialsDataImplPort = new QName("http://getequipcodes.api.adam.hitina.net/", "GetMaterialsDataImplPort");

    static {
        URL url = null;
        try {
            ResourceBundle resource = ResourceBundle.getBundle("config.webservice");
            String iP = resource.getString("WZGL.IP").trim();
            url = new URL(iP + "/czx-web/webservice/getequipcodes?wsdl");

            //pro1
//            url = new URL("http://10.0.52.206:7001/czx-web/webservice/getequipcodes?wsdl");
            //pro2
//            url = new URL("http://10.0.52.207:7001/czx-web/webservice/getequipcodes?wsdl");
            //测试地址
//            url = new URL("http://10.0.42.7:7001/czx-web/webservice/getequipcodes?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetMaterialsDataImplService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://10.0.52.206:7001/czx-web/webservice/getequipcodes?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetMaterialsDataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetMaterialsDataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetMaterialsDataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetMaterialsDataImplService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetMaterialsDataImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetMaterialsDataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns GetMaterialsData
     */
    @WebEndpoint(name = "GetMaterialsDataImplPort")
    public GetMaterialsData getGetMaterialsDataImplPort() {
        return super.getPort(GetMaterialsDataImplPort, GetMaterialsData.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns GetMaterialsData
     */
    @WebEndpoint(name = "GetMaterialsDataImplPort")
    public GetMaterialsData getGetMaterialsDataImplPort(WebServiceFeature... features) {
        return super.getPort(GetMaterialsDataImplPort, GetMaterialsData.class, features);
    }

}
