package com.mine.product.czmtr.ram.asset.taskclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-28T11:02:52.753+08:00
 * Generated source version: 3.3.3
 */
@WebService(targetNamespace = "http://getequipcodes.api.adam.hitina.net/", name = "GetMaterialsData")
@XmlSeeAlso({ObjectFactory.class})
public interface GetMaterialsData {

    @WebMethod
    @RequestWrapper(localName = "getEquipCode", targetNamespace = "http://getequipcodes.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.asset.taskclient.GetEquipCode")
    @ResponseWrapper(localName = "getEquipCodeResponse", targetNamespace = "http://getequipcodes.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.asset.taskclient.GetEquipCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEquipCode(

            @WebParam(name = "arg0", targetNamespace = "")
                    com.mine.product.czmtr.ram.asset.taskclient.CodeBean arg0
    );
}
