package com.mine.product.czmtr.ram.outapi.taskclient.location;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-29T10:37:48.037+08:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://location.api.adam.hitina.net/", name = "LocationMD")
@XmlSeeAlso({ObjectFactory.class})
public interface LocationMD {

    @WebMethod
    @RequestWrapper(localName = "getLocations", targetNamespace = "http://location.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.location.GetLocations")
    @ResponseWrapper(localName = "getLocationsResponse", targetNamespace = "http://location.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.location.GetLocationsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getLocations(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
