package com.mine.product.czmtr.ram.outapi.taskclient.materials;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-27T16:14:07.905+08:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://materials.api.adam.hitina.net/", name = "MaterialsMasterData")
@XmlSeeAlso({ObjectFactory.class})
public interface MaterialsMasterData {

    @WebMethod
    @RequestWrapper(localName = "getMaterials", targetNamespace = "http://materials.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.materials.GetMaterials")
    @ResponseWrapper(localName = "getMaterialsResponse", targetNamespace = "http://materials.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.materials.GetMaterialsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMaterials(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
