package com.mine.product.czmtr.ram.outapi.taskclient.asset;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-27T16:12:46.205+08:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://assetclass.api.adam.hitina.net/", name = "AssetMD")
@XmlSeeAlso({ObjectFactory.class})
public interface AssetMD {

    @WebMethod
    @RequestWrapper(localName = "getAssets", targetNamespace = "http://assetclass.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.asset.GetAssets")
    @ResponseWrapper(localName = "getAssetsResponse", targetNamespace = "http://assetclass.api.adam.hitina.net/", className = "com.mine.product.czmtr.ram.outapi.taskclient.asset.GetAssetsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAssets(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
