package com.mine.product.czmtr.ram.outapi.taskclient.changeAsset;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-11-26T10:19:48.217+08:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://fa.itf.nc/NC_dr_Ixml", name = "NC_dr_IxmlPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NCDrIxmlPortType {

    @WebMethod(operationName = "Login", action = "urn:Login")
    @Action(input = "urn:Login", output = "urn:LoginResponse")
    @RequestWrapper(localName = "Login", targetNamespace = "http://fa.itf.nc/NC_dr_Ixml", className = "nc.itf.fa.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://fa.itf.nc/NC_dr_Ixml", className = "nc.itf.fa.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String login(
            @WebParam(name = "string", targetNamespace = "")
                    String string,
            @WebParam(name = "string1", targetNamespace = "")
                    String string1
    );
}
